### PR TITLE
Add the packaging metadata to build the zsync-curl snap

### PR DESCRIPTION
**Pull request by come-maiz**
This package will let you publish the latest zsync-curl in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by come-maiz** [comment]
Hey @probonopd !

I was trying to download KDE neon and found that it required your version of zsync to do it over HTTPS.
I appreciate the work you do in AppImage. I don't agree with your approach, but I think it's good to have options, and it would be nice if we all had fun in our projects in a friendly way. So, as I needed a snap for zsync, I thought about asking for your feedback on the things that we are doing here. Looking at all the work that you have done, I will value your opinion a lot.

To test this in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/zsync-curl
    $ cd zsync-curl
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous

If you would like to get it in the store, and at the same time take a look at what we are doing on that area, you can use https://build.snapcraft.io/ after the snapcraft.yaml is in your repo.

pura vida.

**Comment by probonopd** [comment]
Hi @elopio what does `confinement: strict` mean? Does it affect the software's ability to read and write from random locations in the filesystem?

Even after reading https://snapcraft.io/docs/build-snaps/debugging it is not clear to me what `confinement: strict` actually does.

**Comment by come-maiz** [comment]
Thanks for reviewing it @probonopd.

strict means that it will be fully confined. By default, it will just be able to read and write to ~/snap/zsync-curl/. We allow snaps to get more permissions through the interfaces, that's the `plugs` section you see there in the yaml. The `home` interface is a temporary one to allow snaps to read and write to /home/<user>, except the hidden dot files and the snap directory.

You can read more about it here: https://snapcraft.io/docs/reference/confinement

We are discussing about the right way to let the user control which paths the snap can access, using what we learned with the content hub in the phone and the gnome portal. The first implementation will be probably to support [editors](https://forum.snapcraft.io/t/support-for-editors-and-similar-in-strict-mode/253/6).

**Comment by come-maiz** [comment]
Thanks for the merge! I'm eager to here your feedback, and to be able to install it from the store.

**Pull request merged**
