### PR TITLE
Add '-f' option to follow a redirection

### PR DESCRIPTION
**Pull request by pamarcos**
There is already a `-r` option that simply prints out the URL redirected to. However, that's not very useful if we don't want to call zsync_curl twice (one for resolving the redirection and another one with the redirected URL). Hence, I think having a `-f` option to follow what you already know is a URL with a redirection is useful.

Ideally, the redirection should be done automatically if needed. Unfortunately, at the moment the `get_redirected_url` method is dumping the body to stdout. Hence, as a temporary solution the `-f` option does the job.

### CODE REVIEW

**Comment by TheAssassin** [comment]
I don't fully understand your comment, but as far as I can see I don't see a reason for adding a flag here. Are you saying zsync_curl isn't following redirections of URLs?

Also, I am not a fan of adding features to zsync_curl. This project is essentially dead, has been superseded by https://github.com/TheAssassin/zsync2 (which works really stable as of now), and investing time in maintaining this project doesn't seem useful for AppImage. We should probably add a note about that.

**Comment by probonopd** [comment]
This project is no longer maintained, I recommend its successor [zsync2](https://github.com/TheAssassin/zsync2) which was started to fix the shortcomings of this code base.

**Comment by pamarcos** [comment]
> I don't fully understand your comment, but as far as I can see I don't see a reason for adding a flag here. Are you saying zsync_curl isn't following redirections of URLs?

Exactly, zsync_curl is not following redirections.

I think zsync2 is a good idea, but at the moment it doesn't even have a binary to use zsync, or am I missing something?

**Comment by probonopd** [comment]
A binary is available at https://github.com/TheAssassin/zsync2/releases

**Comment by pamarcos** [comment]
Apologies, when I built it last time I probably missed the binary in the src folder (along with libzsync2).

I will move to zsync2 and the `rewrite` version of AppImageUpdate as soon as I have some spare time. Thank you guys for your work 👍

**Comment by TheAssassin** [comment]
Great to hear that. Thanks for your understanding. And by the way, zsync2 [actually resolves redirections properly](https://github.com/TheAssassin/zsync2/blob/master/src/zsclient.cpp#L413-L419).

**Pull request closed without merging**
